wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: epoch
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
      - 3
    - 1: valid_loss
      5: 1
      6:
      - 1
      - 3
    python_version: 3.9.7
    start_time: 1657729084
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 2
      - 3
      - 55
      - 77
      3:
      - 1
      - 7
      4: 3.9.7
      5: 0.12.21
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 128
data_dir:
  desc: null
  value: data/
epochs:
  desc: null
  value: 10
gnn_hidden_dims:
  desc: null
  value: 64
gnn_num_blocks:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.001
mlp_hidden_dims:
  desc: null
  value:
  - 128
  - 128
  - 128
  - 128
model:
  desc: null
  value: gnn
seed:
  desc: null
  value: 42
